import {
  DayOfWeek,
  Ingredient,
  PaymentMethod,
  PrismaClient,
  ShippingMethod,
} from "@prisma/client"

const prisma = new PrismaClient()

const shopSettingsId = process.env.SHOP_SETTINGS_ID

export const ingredientsData: Omit<
  Ingredient,
  "id" | "createdAt" | "updatedAt"
>[] = [
  {
    name: "Aceite",
    waste: 0,
    price: 1500,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "LITER",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Aji molido",
    waste: 0,
    price: 0,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Ajo en polvo",
    waste: 0,
    price: 0,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Almidón de maíz",
    waste: 0,
    price: 0.96,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Arroz parboil",
    waste: 0,
    price: 3500,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Arroz carnaroli",
    waste: 0,
    price: 3000,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Arroz doble carolina",
    waste: 0,
    price: 3000,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Arvejas congeladas",
    waste: 0,
    price: 1971,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Bandeja 103",
    waste: 0,
    price: 0.07,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "UNIT",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Batata",
    waste: 20,
    price: 650,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Berenjenas",
    waste: 0.5,
    price: 700,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Brócoli",
    waste: 0,
    price: 2800,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Calabaza anco",
    waste: 30,
    price: 450,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Carne picada",
    waste: 0,
    price: 5500,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Carre de cerdo",
    waste: 15,
    price: 6300,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Cebolla",
    waste: 15,
    price: 630,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Cebolla de verdeo",
    waste: 30,
    price: 700,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Champiñones",
    waste: 0,
    price: 4.5,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Choclo congelado",
    waste: 0,
    price: 2300,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Condimento para arroz",
    waste: 0,
    price: 0,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Crema de leche",
    waste: 0,
    price: 4.0,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "MILLILITER",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Cúrcuma",
    waste: 0,
    price: 0,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Curry",
    waste: 0,
    price: 0,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Espinaca congelada",
    waste: 0,
    price: 2100,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Fécula de mandioca",
    waste: 0,
    price: 0.9,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Filet de merluza",
    waste: 0,
    price: 3000,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Garbanzos secos",
    waste: 0,
    price: 1131,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Harina de arroz",
    waste: 0,
    price: 700,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Huevo",
    waste: 0,
    price: 0.11,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "UNIT",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Jengibre",
    waste: 0,
    price: 0,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Lata de tomate",
    waste: 0,
    price: 2.0,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "UNIT",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Leche",
    waste: 0,
    price: 900,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "LITER",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Leche en polvo",
    waste: 0,
    price: 4000,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Lentejas secas",
    waste: 0,
    price: 2500,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Miel",
    waste: 0,
    price: 3000,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Mix de vegetales",
    waste: 0,
    price: 2500,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Morron rojo",
    waste: 20,
    price: 1500,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Morron verde",
    waste: 20,
    price: 1500,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Mostaza",
    waste: 0,
    price: 1.8,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Nuez Moscada",
    waste: 0,
    price: 0,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Oregano",
    waste: 0,
    price: 0,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Papa",
    waste: 35,
    price: 1200,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Pasta de chimichurri picante",
    waste: 0,
    price: 1.8,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Pechugas de pollo",
    waste: 10,
    price: 4800,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Perejil",
    waste: 0,
    price: 0,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Pimenton",
    waste: 0,
    price: 0,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Pimienta",
    waste: 0,
    price: 0,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Polenta",
    waste: 0,
    price: 540,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Provenzal",
    waste: 0,
    price: 0,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Puré de tomate",
    waste: 0,
    price: 1000,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Queso blanco",
    waste: 0,
    price: 2800,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Quesos duros",
    waste: 0.7,
    price: 4500,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Quesos frescos",
    waste: 0,
    price: 4300,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Rebozador aglu",
    waste: 0,
    price: 1500,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Rebozador natuzen",
    waste: 0,
    price: 2640,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Ricota",
    waste: 0,
    price: 1800,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Sal",
    waste: 0,
    price: 270,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Salsa barbacoa",
    waste: 0,
    price: 2.0,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Tapa 103",
    waste: 0,
    price: 0.15,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Tomate",
    waste: 15,
    price: 900,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Zanahoria",
    waste: 25,
    price: 800,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Zapallito redondo",
    waste: 10,
    price: 950,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Aceto reducción",
    waste: 0,
    price: 0,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Salsa de soja",
    waste: 0,
    price: 0,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "MILLILITER",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Arroz integral",
    waste: 0,
    price: 3000,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Brote de soja",
    waste: 0,
    price: 0,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Carne para guiso",
    waste: 0,
    price: 6000,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "MANTECA",
    waste: 0,
    price: 6250,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Lamina de folez 20 x 25 el kilo",
    waste: 0,
    price: 2.499,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Banana",
    waste: 0,
    price: 2000,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
]

const operationalHours = [
  { dayOfWeek: DayOfWeek.MONDAY, startTime: "09:00", endTime: "17:00" },
  { dayOfWeek: DayOfWeek.TUESDAY, startTime: "09:00", endTime: "17:00" },
  { dayOfWeek: DayOfWeek.WEDNESDAY, startTime: "09:00", endTime: "17:00" },
  { dayOfWeek: DayOfWeek.THURSDAY, startTime: "09:00", endTime: "17:00" },
  { dayOfWeek: DayOfWeek.FRIDAY, startTime: "09:00", endTime: "17:00" },
  { dayOfWeek: DayOfWeek.SATURDAY, startTime: "10:00", endTime: "14:00" },
  { dayOfWeek: DayOfWeek.SUNDAY, startTime: null, endTime: null }, // Closed
]

async function main() {
  if (!shopSettingsId) {
    console.error("Es necesario el ID de la configuración de tienda.")
    return
  }

  for (const ingredient of ingredientsData) {
    await prisma.ingredient.upsert({
      where: { name: ingredient.name },
      update: ingredient,
      create: ingredient,
    })
  }

  await prisma.shopSettings.upsert({
    where: { id: shopSettingsId },
    update: {},
    create: {
      id: shopSettingsId,
      allowedPaymentMethods: [PaymentMethod.CASH, PaymentMethod.BANK_TRANSFER],
      branches: {
        create: [
          {
            label: "Sucursal Agronomía",
            branchType: "RETAIL",
            province: "Ciudad Autónoma de Buenos Aires",
            municipality: "CABA",
            locality: "Agronomía",
            addressStreet: "Main St",
            addressNumber: 123,
            phoneNumber: "+54 11 1234 5678",
            email: null,
            latitude: null,
            longitude: null,
            managerName: null,
            timezone: "America/Argentina/Buenos_Aires",
            isActive: true,
            description: "Retail branch located in Agronomía.",
            image: null,
            operationalHours: {
              create: operationalHours?.map((hours) => ({
                dayOfWeek: hours.dayOfWeek,
                startTime: hours.startTime || null,
                endTime: hours.endTime || null,
              })),
            },
          },
        ],
      },
      shippingSettings: {
        create: {
          allowedShippingMethods: [
            ShippingMethod.DELIVERY,
            ShippingMethod.TAKE_AWAY,
          ],
          minProductsQuantityForDelivery: 10,
        },
      },
    },
  })
}

main()
  .catch((error) => {
    console.error(error)
    process.exit(1)
  })
  .finally(() => prisma.$disconnect)
