import {
  DayOfWeek,
  Ingredient,
  PaymentMethod,
  ActionKey,
  SubjectKey,
  PrismaClient,
  ShippingMethod,
  ProductRecipeType,
  ShopBranch,
  Shop,
  ShopCategory,
} from "@prisma/client"

const prisma = new PrismaClient()

const shopSettingsId = process.env.SHOP_SETTINGS_ID

const permissions: {
  name: string
  actionKey: ActionKey
  subjectKey: SubjectKey
}[] = [
  { name: "Ver Dashboard", actionKey: "view", subjectKey: "analytics" },

  { name: "Ver productos", actionKey: "view", subjectKey: "products" },
  { name: "Crear productos", actionKey: "create", subjectKey: "products" },
  { name: "Actualizar productos", actionKey: "update", subjectKey: "products" },
  { name: "Eliminar productos", actionKey: "delete", subjectKey: "products" },
  { name: "Exportar productos", actionKey: "export", subjectKey: "products" },

  { name: "Ver categorías", actionKey: "view", subjectKey: "categories" },
  { name: "Crear categorías", actionKey: "create", subjectKey: "categories" },
  {
    name: "Actualizar categorías",
    actionKey: "update",
    subjectKey: "categories",
  },
  {
    name: "Eliminar categorías",
    actionKey: "delete",
    subjectKey: "categories",
  },
  {
    name: "Exportar categorías",
    actionKey: "export",
    subjectKey: "categories",
  },

  { name: "Ver promociones", actionKey: "view", subjectKey: "promotions" },
  { name: "Crear promociones", actionKey: "create", subjectKey: "promotions" },
  {
    name: "Actualizar promociones",
    actionKey: "update",
    subjectKey: "promotions",
  },
  {
    name: "Eliminar promociones",
    actionKey: "delete",
    subjectKey: "promotions",
  },
  {
    name: "Exportar promociones",
    actionKey: "export",
    subjectKey: "promotions",
  },

  { name: "Ver pedidos", actionKey: "view", subjectKey: "orders" },
  { name: "Crear pedidos", actionKey: "create", subjectKey: "orders" },
  { name: "Actualizar pedidos", actionKey: "update", subjectKey: "orders" },
  { name: "Eliminar pedidos", actionKey: "delete", subjectKey: "orders" },
  { name: "Exportar pedidos", actionKey: "export", subjectKey: "orders" },

  { name: "Ver clientes", actionKey: "view", subjectKey: "customers" },
  { name: "Crear clientes", actionKey: "create", subjectKey: "customers" },
  { name: "Actualizar clientes", actionKey: "update", subjectKey: "customers" },
  { name: "Eliminar clientes", actionKey: "delete", subjectKey: "customers" },
  { name: "Exportar clientes", actionKey: "export", subjectKey: "customers" },

  {
    name: "Ver direcciones de clientes",
    actionKey: "view",
    subjectKey: "customerAddresses",
  },
  {
    name: "Crear direcciones de clientes",
    actionKey: "create",
    subjectKey: "customerAddresses",
  },
  {
    name: "Actualizar direcciones de clientes",
    actionKey: "update",
    subjectKey: "customerAddresses",
  },
  {
    name: "Eliminar direcciones de clientes",
    actionKey: "delete",
    subjectKey: "customerAddresses",
  },
  {
    name: "Exportar direcciones de clientes",
    actionKey: "export",
    subjectKey: "customerAddresses",
  },

  { name: "Ver tiendas", actionKey: "view", subjectKey: "shops" },
  {
    name: "Crear tiendas",
    actionKey: "create",
    subjectKey: "shops",
  },
  {
    name: "Actualizar tiendas",
    actionKey: "update",
    subjectKey: "shops",
  },
  {
    name: "Eliminar tiendas",
    actionKey: "delete",
    subjectKey: "shops",
  },
  {
    name: "Exportar tiendas",
    actionKey: "export",
    subjectKey: "shops",
  },

  {
    name: "Ver configuración de la tienda",
    actionKey: "view",
    subjectKey: "shopSettings",
  },
  {
    name: "Actualizar configuración de la tienda",
    actionKey: "update",
    subjectKey: "shopSettings",
  },
  {
    name: "Exportar configuración de la tienda",
    actionKey: "export",
    subjectKey: "shopSettings",
  },

  { name: "Ver sucursales", actionKey: "view", subjectKey: "shopBranches" },
  { name: "Crear sucursales", actionKey: "create", subjectKey: "shopBranches" },
  {
    name: "Actualizar sucursales",
    actionKey: "update",
    subjectKey: "shopBranches",
  },
  {
    name: "Eliminar sucursales",
    actionKey: "delete",
    subjectKey: "shopBranches",
  },
  {
    name: "Exportar sucursales",
    actionKey: "export",
    subjectKey: "shopBranches",
  },

  {
    name: "Ver configuración de envíos",
    actionKey: "view",
    subjectKey: "shippingSettings",
  },
  {
    name: "Actualizar configuración de envíos",
    actionKey: "update",
    subjectKey: "shippingSettings",
  },
  {
    name: "Exportar configuración de envíos",
    actionKey: "export",
    subjectKey: "shippingSettings",
  },
  {
    name: "Ver zonas de envío",
    actionKey: "view",
    subjectKey: "shippingZones",
  },
  {
    name: "Crear zonas de envío",
    actionKey: "create",
    subjectKey: "shippingZones",
  },
  {
    name: "Actualizar zonas de envío",
    actionKey: "update",
    subjectKey: "shippingZones",
  },
  {
    name: "Eliminar zonas de envío",
    actionKey: "delete",
    subjectKey: "shippingZones",
  },
  {
    name: "Exportar zonas de envío",
    actionKey: "export",
    subjectKey: "shippingZones",
  },

  { name: "Ver ingredientes", actionKey: "view", subjectKey: "ingredients" },
  {
    name: "Crear ingredientes",
    actionKey: "create",
    subjectKey: "ingredients",
  },
  {
    name: "Actualizar ingredientes",
    actionKey: "update",
    subjectKey: "ingredients",
  },
  {
    name: "Eliminar ingredientes",
    actionKey: "delete",
    subjectKey: "ingredients",
  },
  {
    name: "Exportar ingredientes",
    actionKey: "export",
    subjectKey: "ingredients",
  },

  { name: "Ver recetas", actionKey: "view", subjectKey: "recipes" },
  { name: "Crear recetas", actionKey: "create", subjectKey: "recipes" },
  { name: "Actualizar recetas", actionKey: "update", subjectKey: "recipes" },
  { name: "Eliminar recetas", actionKey: "delete", subjectKey: "recipes" },
  { name: "Exportar recetas", actionKey: "export", subjectKey: "recipes" },

  { name: "Ver roles", actionKey: "view", subjectKey: "roles" },
  { name: "Crear roles", actionKey: "create", subjectKey: "roles" },
  { name: "Actualizar roles", actionKey: "update", subjectKey: "roles" },
  { name: "Eliminar roles", actionKey: "delete", subjectKey: "roles" },
  { name: "Exportar roles", actionKey: "export", subjectKey: "roles" },

  { name: "Ver permisos", actionKey: "view", subjectKey: "permissions" },
  { name: "Crear permisos", actionKey: "create", subjectKey: "permissions" },
  {
    name: "Actualizar permisos",
    actionKey: "update",
    subjectKey: "permissions",
  },
  { name: "Eliminar permisos", actionKey: "delete", subjectKey: "permissions" },
  { name: "Exportar permisos", actionKey: "export", subjectKey: "permissions" },

  { name: "Ver usuarios", actionKey: "view", subjectKey: "users" },
  { name: "Crear usuarios", actionKey: "create", subjectKey: "users" },
  { name: "Actualizar usuarios", actionKey: "update", subjectKey: "users" },
  { name: "Eliminar usuarios", actionKey: "delete", subjectKey: "users" },
  { name: "Exportar usuarios", actionKey: "export", subjectKey: "users" },

  {
    name: "Crear tipo de receta",
    actionKey: "create",
    subjectKey: "productRecipeTypes",
  },
  {
    name: "Actualizar tipo de receta",
    actionKey: "update",
    subjectKey: "productRecipeTypes",
  },
  {
    name: "Eliminar tipo de receta",
    actionKey: "delete",
    subjectKey: "productRecipeTypes",
  },
  {
    name: "Exportar tipo de receta",
    actionKey: "export",
    subjectKey: "productRecipeTypes",
  },
]

const shops: Omit<Shop, "id" | "createdAt" | "updatedAt">[] = [
  {
    name: "Viandas",
    key: "foods",
    title: "Tienda de viandas",
    description: "Ecommerce de viandas.",
    bannerImage: "",
    shopCategory: ShopCategory.FOOD,
    isActive: true,
  },
  {
    name: "Pastelería",
    key: "bakery",
    title: "Tienda de pastelería",
    description: "Ecommerce de pastelería.",
    bannerImage: "",
    shopCategory: ShopCategory.BAKERY,
    isActive: true,
  },
]

const ingredientsData: Omit<Ingredient, "id" | "createdAt" | "updatedAt">[] = [
  {
    name: "Aceite",
    waste: 0,
    price: 1500,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "LITER",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Aji molido",
    waste: 0,
    price: 0,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Ajo en polvo",
    waste: 0,
    price: 0,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Almidón de maíz",
    waste: 0,
    price: 0.96,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Arroz parboil",
    waste: 0,
    price: 3500,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Arroz carnaroli",
    waste: 0,
    price: 3000,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Arroz doble carolina",
    waste: 0,
    price: 3000,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Arvejas congeladas",
    waste: 0,
    price: 1971,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Bandeja 103",
    waste: 0,
    price: 0.07,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "UNIT",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Batata",
    waste: 20,
    price: 650,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Berenjenas",
    waste: 0.5,
    price: 700,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Brócoli",
    waste: 0,
    price: 2800,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Calabaza anco",
    waste: 30,
    price: 450,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Carne picada",
    waste: 0,
    price: 5500,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Carre de cerdo",
    waste: 15,
    price: 6300,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Cebolla",
    waste: 15,
    price: 630,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Cebolla de verdeo",
    waste: 30,
    price: 700,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Champiñones",
    waste: 0,
    price: 4.5,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Choclo congelado",
    waste: 0,
    price: 2300,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Condimento para arroz",
    waste: 0,
    price: 0,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Crema de leche",
    waste: 0,
    price: 4.0,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "MILLILITER",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Cúrcuma",
    waste: 0,
    price: 0,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Curry",
    waste: 0,
    price: 0,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Espinaca congelada",
    waste: 0,
    price: 2100,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Fécula de mandioca",
    waste: 0,
    price: 0.9,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Filet de merluza",
    waste: 0,
    price: 3000,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Garbanzos secos",
    waste: 0,
    price: 1131,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Harina de arroz",
    waste: 0,
    price: 700,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Huevo",
    waste: 0,
    price: 0.11,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "UNIT",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Jengibre",
    waste: 0,
    price: 0,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Lata de tomate",
    waste: 0,
    price: 2.0,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "UNIT",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Leche",
    waste: 0,
    price: 900,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "LITER",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Leche en polvo",
    waste: 0,
    price: 4000,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Lentejas secas",
    waste: 0,
    price: 2500,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Miel",
    waste: 0,
    price: 3000,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Mix de vegetales",
    waste: 0,
    price: 2500,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Morron rojo",
    waste: 20,
    price: 1500,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Morron verde",
    waste: 20,
    price: 1500,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Mostaza",
    waste: 0,
    price: 1.8,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Nuez Moscada",
    waste: 0,
    price: 0,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Oregano",
    waste: 0,
    price: 0,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Papa",
    waste: 35,
    price: 1200,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Pasta de chimichurri picante",
    waste: 0,
    price: 1.8,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Pechugas de pollo",
    waste: 10,
    price: 4800,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Perejil",
    waste: 0,
    price: 0,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Pimenton",
    waste: 0,
    price: 0,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Pimienta",
    waste: 0,
    price: 0,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Polenta",
    waste: 0,
    price: 540,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Provenzal",
    waste: 0,
    price: 0,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Puré de tomate",
    waste: 0,
    price: 1000,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Queso blanco",
    waste: 0,
    price: 2800,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Quesos duros",
    waste: 0.7,
    price: 4500,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Quesos frescos",
    waste: 0,
    price: 4300,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Rebozador aglu",
    waste: 0,
    price: 1500,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Rebozador natuzen",
    waste: 0,
    price: 2640,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Ricota",
    waste: 0,
    price: 1800,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Sal",
    waste: 0,
    price: 270,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Salsa barbacoa",
    waste: 0,
    price: 2.0,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Tapa 103",
    waste: 0,
    price: 0.15,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Tomate",
    waste: 15,
    price: 900,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Zanahoria",
    waste: 25,
    price: 800,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Zapallito redondo",
    waste: 10,
    price: 950,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Aceto reducción",
    waste: 0,
    price: 0,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Salsa de soja",
    waste: 0,
    price: 0,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "MILLILITER",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Arroz integral",
    waste: 0,
    price: 3000,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Brote de soja",
    waste: 0,
    price: 0,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Carne para guiso",
    waste: 0,
    price: 6000,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "MANTECA",
    waste: 0,
    price: 6250,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Lamina de folez 20 x 25 el kilo",
    waste: 0,
    price: 2.499,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
  {
    name: "Banana",
    waste: 0,
    price: 2000,
    brand: null,
    amountPerMeasurement: 1,
    measurement: "KILOGRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
    calories: 0,
  },
]

const productRecipesTypes: Omit<ProductRecipeType, "id">[] = [
  { name: "Principal" },
  { name: "Guarnición" },
  { name: "Salsa" },
  { name: "Relleno" },
  { name: "Masa" },
]

const branchesOperationalHours = [
  { dayOfWeek: DayOfWeek.MONDAY, startTime: "09:00", endTime: "17:00" },
  { dayOfWeek: DayOfWeek.TUESDAY, startTime: "09:00", endTime: "17:00" },
  { dayOfWeek: DayOfWeek.WEDNESDAY, startTime: "09:00", endTime: "17:00" },
  { dayOfWeek: DayOfWeek.THURSDAY, startTime: "09:00", endTime: "17:00" },
  { dayOfWeek: DayOfWeek.FRIDAY, startTime: "09:00", endTime: "17:00" },
  { dayOfWeek: DayOfWeek.SATURDAY, startTime: "10:00", endTime: "14:00" },
  { dayOfWeek: DayOfWeek.SUNDAY, startTime: null, endTime: null }, // Closed
]

const shopsOperationalHours = [
  { dayOfWeek: DayOfWeek.MONDAY, startTime: null, endTime: null },
  { dayOfWeek: DayOfWeek.TUESDAY, startTime: null, endTime: null },
  { dayOfWeek: DayOfWeek.WEDNESDAY, startTime: null, endTime: null },
  { dayOfWeek: DayOfWeek.THURSDAY, startTime: null, endTime: null },
  { dayOfWeek: DayOfWeek.FRIDAY, startTime: "00:00", endTime: "23:59" },
  { dayOfWeek: DayOfWeek.SATURDAY, startTime: "00:00", endTime: "23:59" },
  { dayOfWeek: DayOfWeek.SUNDAY, startTime: "00:00", endTime: "23:59" },
]

const shopBranches: Omit<
  ShopBranch,
  "id" | "createdAt" | "updatedAt" | "shopSettingsId"
>[] = [
  {
    label: "Sucursal Agronomía",
    branchType: "RETAIL",
    province: "Ciudad Autónoma de Buenos Aires",
    municipality: "Comuna 15",
    locality: "Agronomía",
    addressStreet: "Main St",
    addressNumber: 123,
    addressFloor: null,
    addressApartment: null,
    postCode: null,
    phoneNumber: "+54 11 1234 5678",
    email: null,
    latitude: null,
    longitude: null,
    managerName: null,
    timezone: "America/Argentina/Buenos_Aires",
    isActive: true,
    description: "Retail branch located in Agronomía.",
    image: null,
  },
]

async function main() {
  if (!shopSettingsId) {
    console.error("Es necesario el ID de la configuración de tienda.")
    return
  }

  const permissionRecords = await Promise.all(
    permissions.map((perm) =>
      prisma.permission.upsert({
        where: {
          actionKey_subjectKey: {
            actionKey: perm.actionKey,
            subjectKey: perm.subjectKey,
          },
        },
        update: {},
        create: perm,
      })
    )
  )

  const permissionMap = Object.fromEntries(
    permissionRecords.map((perm) => [
      `${perm.actionKey}:${perm.subjectKey}`,
      perm.id,
    ])
  )

  await prisma.role.upsert({
    where: { name: "ADMIN" },
    update: {
      group: "STAFF",
      permissions: {
        connect: permissionRecords.map((perm) => ({ id: perm.id })),
      },
    },
    create: {
      name: "ADMIN",
      description: "Administrator with full access",
      group: "STAFF",
      permissions: {
        connect: permissionRecords.map((perm) => ({ id: perm.id })),
      },
    },
  })

  await prisma.role.upsert({
    where: { name: "USER" },
    update: {
      group: "CUSTOMER",
    },
    create: {
      name: "USER",
      description: "Regular user with limited access",
      group: "CUSTOMER",
      permissions: {
        connect: [
          { id: permissionMap["view:products"] },
          { id: permissionMap["view:categories"] },
        ],
      },
    },
  })

  for (const ingredient of ingredientsData) {
    await prisma.ingredient.upsert({
      where: { name: ingredient.name },
      update: ingredient,
      create: ingredient,
    })
  }

  for (const type of productRecipesTypes) {
    await prisma.productRecipeType.upsert({
      where: { name: type.name },
      update: type,
      create: type,
    })
  }

  await prisma.shopSettings.upsert({
    where: { id: shopSettingsId },
    update: {},
    create: {
      id: shopSettingsId,
      allowedPaymentMethods: [PaymentMethod.CASH, PaymentMethod.BANK_TRANSFER],
      shippingSettings: {
        create: {
          allowedShippingMethods: [
            ShippingMethod.DELIVERY,
            ShippingMethod.TAKE_AWAY,
          ],
          minProductsQuantityForDelivery: 10,
        },
      },
    },
  })

  const createdBranches = []
  for (const branch of shopBranches) {
    const createdBranch = await prisma.shopBranch.upsert({
      where: { label: branch.label },
      update: {},
      create: {
        label: branch.label,
        branchType: branch.branchType,
        province: branch.province,
        municipality: branch.municipality,
        locality: branch.locality,
        addressStreet: branch.addressStreet,
        addressNumber: branch.addressNumber,
        phoneNumber: branch.phoneNumber,
        email: branch.email,
        latitude: branch.latitude,
        longitude: branch.longitude,
        managerName: branch.managerName,
        timezone: branch.timezone,
        isActive: branch.isActive,
        description: branch.description,
        image: branch.image,
        operationalHours: {
          create: branchesOperationalHours.map((hours) => ({
            dayOfWeek: hours.dayOfWeek,
            startTime: hours.startTime || null,
            endTime: hours.endTime || null,
          })),
        },
      },
    })
    createdBranches.push(createdBranch)
  }

  for (const shopData of shops) {
    await prisma.shop.upsert({
      where: { name: shopData.name },
      update: {},
      create: {
        ...shopData,
        operationalHours: {
          create: shopsOperationalHours.map((hours) => ({
            dayOfWeek: hours.dayOfWeek,
            startTime: hours.startTime || null,
            endTime: hours.endTime || null,
          })),
        },
      },
    })
  }
}

main()
  .catch((error) => {
    console.error(error)
    process.exit(1)
  })
  .finally(() => prisma.$disconnect)
