import { Ingredient, PrismaClient } from "@prisma/client"

const prisma = new PrismaClient()

export const ingredientsData: Omit<
  Ingredient,
  "id" | "createdAt" | "updatedAt"
>[] = [
  {
    name: "Aceite",
    waste: 0,
    price: 1.5,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Aji molido",
    waste: 0,
    price: 0,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Ajo en polvo",
    waste: 0,
    price: 0,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Almidón de maíz",
    waste: 0,
    price: 0.96,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Arroz parboil",
    waste: 0,
    price: 3.5,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Arroz carnaroli",
    waste: 0,
    price: 3.0,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Arroz doble carolina",
    waste: 0,
    price: 3.0,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Arvejas congeladas",
    waste: 0,
    price: 1.971,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Bandeja 103",
    waste: 0,
    price: 0.07,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Batata",
    waste: 0.2,
    price: 0.65,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Berenjenas",
    waste: 0.05,
    price: 0.7,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Brócoli",
    waste: 0,
    price: 2.8,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Calabaza anco",
    waste: 0.3,
    price: 0.45,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Carne picada",
    waste: 0,
    price: 5.5,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Carre de cerdo",
    waste: 0.15,
    price: 6.3,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Cebolla",
    waste: 0.15,
    price: 0.63,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Cebolla de verdeo",
    waste: 0.3,
    price: 0.7,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Champiñones",
    waste: 0,
    price: 4.5,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Choclo congelado",
    waste: 0,
    price: 2.3,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Condimento para arroz",
    waste: 0,
    price: 0,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Crema de leche",
    waste: 0,
    price: 4.0,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Cúrcuma",
    waste: 0,
    price: 0,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Curry",
    waste: 0,
    price: 0,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Espinaca congelada",
    waste: 0,
    price: 2.1,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Fécula de mandioca",
    waste: 0,
    price: 0.9,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Filet de merluza",
    waste: 0,
    price: 3.0,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Garbanzos secos",
    waste: 0,
    price: 1.131,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Harina de arroz",
    waste: 0,
    price: 0.7,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Huevo",
    waste: 0,
    price: 0.11,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Jengibre",
    waste: 0,
    price: 0,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Lata de tomate",
    waste: 0,
    price: 2.0,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Leche",
    waste: 0,
    price: 0.9,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Leche en polvo",
    waste: 0,
    price: 4.0,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Lentejas secas",
    waste: 0,
    price: 2.5,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Miel",
    waste: 0,
    price: 3.0,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Mix de vegetales",
    waste: 0,
    price: 2.5,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Morron rojo",
    waste: 0.2,
    price: 1.5,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Morron verde",
    waste: 0.2,
    price: 1.5,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Mostaza",
    waste: 0,
    price: 1.8,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Nuez Moscada",
    waste: 0,
    price: 0,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Oregano",
    waste: 0,
    price: 0,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Papa",
    waste: 0.35,
    price: 1.2,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Pasta de chimichurri picante",
    waste: 0,
    price: 1.8,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Pechugas de pollo",
    waste: 0.1,
    price: 4.8,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Peregil",
    waste: 0,
    price: 0,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Pimenton",
    waste: 0,
    price: 0,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Pimienta",
    waste: 0,
    price: 0,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Polenta",
    waste: 0,
    price: 0.54,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Provensal",
    waste: 0,
    price: 0,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Pure de tomate",
    waste: 0,
    price: 1.0,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Queso blanco",
    waste: 0,
    price: 2.8,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Quesos duros",
    waste: 0.07,
    price: 4.5,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Quesos frescos",
    waste: 0,
    price: 4.3,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Rebozador aglu",
    waste: 0,
    price: 1.5,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Rebozador natuzen",
    waste: 0,
    price: 2.64,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Ricota",
    waste: 0,
    price: 1.8,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Sal",
    waste: 0,
    price: 0.27,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Salsa barbacoa",
    waste: 0,
    price: 2.0,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Tapa 103",
    waste: 0,
    price: 0.15,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Tomate",
    waste: 0.15,
    price: 0.9,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Zanahoria",
    waste: 0.25,
    price: 0.8,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Zapallito redondo",
    waste: 0.1,
    price: 0.95,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Aceto reducción",
    waste: 0,
    price: 0,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Salsa de soja",
    waste: 0,
    price: 0,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Arroz integral",
    waste: 0,
    price: 3.0,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Brote de soja",
    waste: 0,
    price: 0,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Carne para guiso",
    waste: 0,
    price: 6.0,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "MANTECA",
    waste: 0,
    price: 6.25,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Lamina de folez 20 x 25 el kilo",
    waste: 0,
    price: 2.499,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
  {
    name: "Banana",
    waste: 0,
    price: 2.0,
    unit: "GRAM",
    carbs: 0,
    proteins: 0,
    fats: 0,
    fiber: 0,
  },
]

async function main() {
  for (const ingredient of ingredientsData) {
    await prisma.ingredient.upsert({
      where: { name: ingredient.name },
      update: ingredient,
      create: ingredient,
    })
  }
}

main()
  .catch((error) => {
    console.error(error)
    process.exit(1)
  })
  .finally(() => prisma.$disconnect)
