import type { Metadata } from "next"
import { Inter as FontSans } from "next/font/google"
import "./globals.css"
import { cn } from "@/lib/utils"
import { Toaster } from "@/components/ui/toaster"
import { ConfirmationProvider } from "@/components/confirmation-provider"
import { ReactNode } from "react"
import { SessionProvider } from "next-auth/react"
import { auth } from "@/lib/auth/auth"

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})
export const metadata: Metadata = {
  title: "Máxima Nutrición",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  const session = await auth()

  return (
    <html lang='en'>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <SessionProvider session={session}>
          <ConfirmationProvider>
            {children}
            <Toaster />
          </ConfirmationProvider>
        </SessionProvider>
      </body>
    </html>
  )
}
