export const menuData = [
  {
    id: "1",
    category: "Vegetarianos (5) 🥕",
    items: [
      {
        id: "1",
        name: "Risoto de Calabaza",
        description:
          "Delicioso risoto cremoso con trozos de calabaza, arroz Arborio y un toque de parmesano.",
        price: 3600,
        promotionalPrice: 0,
        featured: false,
        stock: true,
        show: true,
        image: "img/rissoto.jpg",
        recipeId: null,
        createdAt: new Date("2024-07-19T12:00:00Z"),
        updatedAt: new Date("2024-07-19T12:00:00Z"),
        // options: [
        //   { value: "con-sal", label: "Con Sal" },
        //   { value: "sin-sal", label: "Sin Sal" },
        // ],
      },
      {
        id: "2",
        name: "Hamburguesa de arroz y espinaca",
        description:
          "Sabrosa hamburguesa hecha con arroz y espinaca, perfecta para una opción saludable y deliciosa.",
        price: 3300,
        promotionalPrice: 0,
        featured: false,
        stock: true,
        show: true,
        image: "img/hambarroz.jpg",
        recipeId: null,
        createdAt: new Date("2024-07-19T12:00:00Z"),
        updatedAt: new Date("2024-07-19T12:00:00Z"),
        // options: [
        //   { value: "con-sal", label: "Con Sal" },
        //   { value: "sin-sal", label: "Sin Sal" },
        // ],
      },
      {
        id: "3",
        name: "Pastel de lentejas y calabaza",
        description:
          "Exquisito pastel a base de lentejas y calabaza, lleno de sabor y nutrientes. Ideal para una comida balanceada y satisfactoria.",
        price: 3800,
        promotionalPrice: 0,
        featured: false,
        stock: true,
        show: true,
        image: "img/pastel-lentejas.jpg",
        recipeId: null,
        createdAt: new Date("2024-07-19T12:00:00Z"),
        updatedAt: new Date("2024-07-19T12:00:00Z"),
        // options: [
        //   { value: "con-sal", label: "Con Sal" },
        //   { value: "sin-sal", label: "Sin Sal" },
        // ],
      },
      {
        id: "4",
        name: "Crepe de espinaca y ricotta",
        description:
          "Deliciosa crepe rellena de espinaca fresca y ricotta cremosa, perfecta para una comida ligera y saludable.",
        price: 3600,
        promotionalPrice: 0,
        featured: false,
        stock: true,
        show: true,
        image: "img/creppes.jpg",
        recipeId: null,
        createdAt: new Date("2024-07-19T12:00:00Z"),
        updatedAt: new Date("2024-07-19T12:00:00Z"),
        // options: [
        //   { value: "con-sal", label: "Con Sal" },
        //   { value: "sin-sal", label: "Sin Sal" },
        // ],
      },
      {
        id: "5",
        name: "Tarta de vegetales",
        description:
          "Apetitosa tarta rellena con una mezcla de vegetales frescos, ideal para una comida nutritiva y llena de sabor.",
        price: 3750,
        promotionalPrice: 0,
        featured: false,
        stock: true,
        show: true,
        image: "img/tartaveg.jpg",
        recipeId: null,
        createdAt: new Date("2024-07-19T12:00:00Z"),
        updatedAt: new Date("2024-07-19T12:00:00Z"),
        // options: [
        //   { value: "con-sal", label: "Con Sal" },
        //   { value: "sin-sal", label: "Sin Sal" },
        // ],
      },
    ],
  },
  {
    id: "2",
    category: "Proteicos (5)",
    items: [
      {
        id: "6",
        name: "Musaka de berenjenas",
        description:
          "Exquisita musaka griega con capas de berenjenas asadas, carne de cordero, salsa de tomate y bechamel gratinada.",
        price: 4000,
        promotionalPrice: 0,
        featured: false,
        stock: true,
        show: true,
        image: "img/musaka-berenj.jpg",
        recipeId: null,
        createdAt: new Date("2024-07-19T12:00:00Z"),
        updatedAt: new Date("2024-07-19T12:00:00Z"),
        // options: [
        //   { value: "con-sal", label: "Con Sal" },
        //   { value: "sin-sal", label: "Sin Sal" },
        // ],
      },
      {
        id: "7",
        name: "Musaka de berenjenas 2",
        description:
          "Exquisita musaka griega con capas de berenjenas asadas, carne de cordero, salsa de tomate y bechamel gratinada.",
        price: 4000,
        image: "img/musaka-berenj.jpg",
        recipeId: null,
        createdAt: new Date("2024-07-19T12:00:00Z"),
        updatedAt: new Date("2024-07-19T12:00:00Z"),
        // options: [
        //   { value: "con-sal", label: "Con Sal" },
        //   { value: "sin-sal", label: "Sin Sal" },
        // ],
      },
    ],
  },
]
